# name: My First Workflow

# on: push

# jobs:
#   say-hello:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Print Hello Message
#         run: echo "Hello, GitHub Actions! My name is ${{ github.repository_owner }}"

#   say-bye:
#     runs-on: ubuntu-latest
#     needs: say-hello
#     steps:
#       - name: Print Bye Message
#         run: echo "Goodbye from second job!"

name: My First Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message
        run: echo "Hello, GitHub Actions! My name is ${{ github.repository_owner }}"

  say-bye:
    runs-on: ubuntu-latest
    needs: say-hello
    steps:
      - name: Print Bye Message
        run: echo "Goodbye from second job!"