# name: My First Workflow

# on: push

# jobs:
#   say-hello:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Print Hello Message
#         run: echo "Hello, GitHub Actions! My name is ${{ github.repository_owner }}"

#   say-bye:
#     runs-on: ubuntu-latest
#     needs: say-hello
#     if: false
#     steps:
#       - name: Print Bye Message
#         run: echo "Goodbye from second job!"

name: My First Workflow

on: push

jobs:
  say-hello:
    runs-on: ubuntu-latest 

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4

      - name: list file
        run: ls

      - name: Print Name
        run: echo "Vridhika"

  say-bye:
    runs-on: ubuntu-latest  
    needs: say-hello

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4

      - name: Print Goodbye
        run: echo "Goodbye"